---
- hosts: all 
  tasks: 
  - name: Run script 
    script: /home/vmunoz/ansible/inventory.ksh
    register: output
  - debug: var=output.stdout_lines
  - local_action: copy content={{output.stdout_lines }} dest="/home/vmunoz/ansible/{{ inventory_hostname}}.json"
  - name: Ansible replace string 
    replace:
      path: /home/vmunoz/ansible/{{ inventory_hostname}}.json
      regexp: '\\'
      replace: ""
    delegate_to: localhost
  - name: Ansible replace string
    replace:
      path: /home/vmunoz/ansible/{{ inventory_hostname}}.json
      regexp: '^..'
      replace: ""
    delegate_to: localhost
  - name: Ansible replace string
    replace:
      path: /home/vmunoz/ansible/{{ inventory_hostname}}.json
      regexp: '[\s\S]{2}$'
      replace: ""
    delegate_to: localhost
  - name: Send to DB 
    with_items: "{{ inventory_hostname}}"
    shell: mongoimport --collection collectionansible --db ansible --file /home/vmunoz/ansible/{{ item }}.json
    delegate_to: localhost 
